# Generated by Django 2.0.1 on 2018-02-04 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startpointpath', models.CharField(max_length=500, verbose_name='Caminho de ponto de partida.')),
            ],
            options={
                'verbose_name_plural': 'Caminhos',
                'verbose_name': 'Caminho',
            },
        ),
        migrations.CreateModel(
            name='PermissionsProfileConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=20, verbose_name='Nome do perfil')),
                ('complementary_path', models.CharField(max_length=500, verbose_name='Complemento do caminho')),
                ('owner', models.CharField(max_length=20, verbose_name='Usuário dono')),
                ('group', models.CharField(max_length=20, verbose_name='Grupo dono')),
            ],
            options={
                'verbose_name_plural': 'Configurações de perfis de permissões',
                'verbose_name': 'Configuração de perfil de permissões',
            },
        ),
        migrations.CreateModel(
            name='UsersForPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Usuário')),
            ],
            options={
                'verbose_name_plural': 'Usuários para caminhos',
                'verbose_name': 'Usuários para caminhos',
            },
        ),
        migrations.AddField(
            model_name='paths',
            name='permission_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.PermissionsProfileConfig'),
        ),
        migrations.AddField(
            model_name='paths',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.UsersForPath'),
        ),
    ]
