# Generated by Django 2.0.1 on 2018-02-13 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredMailDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, verbose_name='Domínio')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.UsersForPath')),
            ],
            options={
                'verbose_name_plural': 'Domínios de e-mail',
                'verbose_name': 'Domínio de e-mail',
            },
        ),
    ]
