# Generated by Django 2.0.1 on 2018-02-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registeredmaildomains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredmaildomains',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UsersForPath'),
        ),
    ]
