# Generated by Django 2.0.1 on 2018-02-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180213_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersforpath',
            name='can_change_password',
            field=models.BooleanField(default=False, verbose_name='Pode alterar a senha'),
        ),
    ]
